periodic_table = {
    1: {"name": "Hydrogen", "symbol": "H", "atomic_mass": 1.008, "group": 1, "period": 1},
    2: {"name": "Helium", "symbol": "He", "atomic_mass": 4.0026, "group": 18, "period": 1},
    3: {"name": "Lithium", "symbol": "Li", "atomic_mass": 6.94, "group": 1, "period": 2},
    4: {"name": "Beryllium", "symbol": "Be", "atomic_mass": 9.0122, "group": 2, "period": 2},
    5: {"name": "Boron", "symbol": "B", "atomic_mass": 10.81, "group": 13, "period": 2},
    6: {"name": "Carbon", "symbol": "C", "atomic_mass": 12.0, "group": 14, "period": 2},
    7: {"name": "Nitrogen", "symbol": "N", "atomic_mass": 14.0, "group": 15, "period": 2},
    8: {"name": "Oxygen", "symbol": "O", "atomic_mass": 16.0, "group": 16, "period": 2},
    9: {"name": "Florine", "symbol": "F", "atomic_mass": 19.0, "group": 17, "period": 2},
    10: {"name": "Neon", "symbol": "N", "atomic_mass": 20.2, "group": 18, "period": 2},
    11: {"name": "Sodium", "symbol": "Na", "atomic_mass": 22.99, "group": 1, "period": 3},
    12: {"name": "Magnesium", "symbol": "Mg", "atomic_mass": 24.3, "group": 2, "period": 3},
    13: {"name": "Aluminium", "symbol": "Al", "atomic_mass": 26.98, "group": 13, "period": 3},
    14: {"name": "Silicon", "symbol": "Si", "atomic_mass": 28.00, "group": 14, "period": 3},
    15: {"name": "Phosphorus", "symbol": "P", "atomic_mass": 30.97, "group": 15, "period": 3},
    16: {"name": "Sulfur", "symbol": "S", "atomic_mass": 32.07, "group": 16, "period": 3},
    17: {"name": "Chlorine", "symbol": "Cl", "atomic_mass": 35.45, "group": 17, "period": 3},
    18: {"name": "Argon", "symbol": "Ar", "atomic_mass": 39.95, "group": 18, "period": 3},
    
}